version: '3.8'

services:
  web:
    build: .
    env_file:
      - .env
    ports: 
      - 3000:3000
    volumes:
      - .:/home/wilton/repos/courses/go/trivia-tutorial
    command: air main.go -b 0.0.0.0
    extra_hosts:
    - host.docker.internal:host-gateway